apiVersion: v1
kind: Service
metadata:
  name: {{ include "kdevops-website.fullname" . }}
  labels:
    {{- include "kdevops-website.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }} # this is 443
      targetPort: 5000
      protocol: TCP
      name: https
      #    - port: 80
      #      targetPort: 5000
      #      protocol: TCP
      #      name: http
  selector:
    {{- include "kdevops-website.selectorLabels" . | nindent 4 }}
